---

- hosts: all
  become: true
  tasks:

  - name: update repository index UBUNTU
    package:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 and libapache2-mod-php package UBUNTU
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
  

  - name: update repository index CENTOS
    package:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache and php package CENTOS
    package:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
  
