---


- hosts: all
  become: true
  tasks:

  - name: UN-INSTALL IPERF 2 ON ALL HOSTS
    apt:
      name: 
        - iperf
      state: absent
    tags: iperf
    when: (ansible_distribution == "Ubuntu")
 
  - name: UN-INSTALL IPERF 2 ON ALL HOSTS
    yum:
      name:
        - iperf
      state: absent
    tags: iperf
    when: (ansible_distribution == "CentOS")

- hosts: database
  become: true
  tasks:

  - name: UN-ISNTALL MARIADB FOR DATABASE SERVER
    package:
      name:
        - mariadb-server
      state: absent
    tags: database

- hosts: fileserver
  become: true
  tasks:

  - name: UN-ISNTALL SAMBA FOR FILESERVER SERVER
    package:
      name:
        - samba
      state: absent
    tags: fileserver
  
