---
- hosts: all
  become: true
  pre_tasks:

  - name: CHECK AND INSTALL UPDATE ON UBUNTU SERVERS
    tags: ubuntu-upgrade
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: CHECK AND INSTALL UPDATE ON CENTOS SERVERS
    tags: centos-upgrade
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

#- hosts: workstation
#  become: true
#  tasks:

#    - name: ISNTALL UNZIP 
#      package:
#        name: unzip

#    - name: INSTALL TERRAFORM
#      unarchive:
#        src: https://releases.hashicorp.com/terraform/1.0.9/terraform_1.0.9_linux_amd64.zip
#        dest: /usr/local/bin
#        remote_src: yes
#        mode: 0755
#        owner: root
#        group: root

    
- hosts: all
  become: true
  roles:
    - base

- hosts: webserver
  become: true
  roles:
    - web_servers

- hosts: database
  become: true
  roles:
    - db_servers

- hosts: fileserver
  become: true
  roles:
    - file_servers
