
  - name: INSTALL APACHE AND PHP FOR WEBSERVER
    tags: webserver
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update-cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: COPY SIMPLE HTML FILE TO WEBSERVER INDEX DIRECTORY
    tags: apache, apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/test.html
      owner: root
      group: root
      mode: 0644  

  - name: START APACHE2 SERVICE ON UBUNTU
    tags: apache, apache2
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"
