- name: COPY IPERF TO REMOTE SERVER
  tags: iperf
  copy:
    src: iperf_2.0.5+dfsg1-2_amd64.deb
    dest: /home/aulian/sources
    owner: root
    group: root
    mode: 0644  

- name: COPY IPERF TO REMOTE SERVER
  tags: iperf
  copy:
    src: iperf_2.0.5+dfsg1-2_amd64.deb
    dest: /home/aulian/sources
    owner: root
    group: root
    mode: 0644  

- name: INSTALL IPERF ON REMOTE SERVER (Ubuntu)
  tags: iperf
  apt:
    deb: /home/aulian/sources/iperf_2.0.5+dfsg1-2_amd64.deb
    force: yes
  when: (ansible_distribution == "Ubuntu")

- name: INSTALL IPERF ON REMOTE SERVER (CENTOS)
  tags: iperf
  yum:
    name: /home/aulian/sources/iperf-2.0.5-13.fc21.x86_64.rpm
    disable_gpg_check: yes
    state: present
  when: ansible_distribution == "CentOS"
